=== darrenyjy/qdhw/DistributedSystem/DSProject4/db/request_queue.dtd
<!ELEMENT RequestQueue (Request*)>
<!ELEMENT Request (RequestID, InputAccountName, InputAccountPassword, InputCreditCardNumber, InputBookName, InputQuantity)>
<!ELEMENT RequestID (#PCDATA)>
<!ELEMENT InputAccountName (#PCDATA)>
<!ELEMENT InputAccountPassword (#PCDATA)>
<!ELEMENT InputCreditCardNumber (#PCDATA)>
<!ELEMENT InputBookName (#PCDATA)>
<!ELEMENT InputQuantity (#PCDATA)>

=== darrenyjy/qdhw/DistributedSystem/DSProject3/db/request_queue.xml
<?xml version="1.0"?>
<!DOCTYPE RequestQueue SYSTEM "request_queue.dtd" >
<RequestQueue>
  <Request>
    <RequestID>1</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>2</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>3</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>4</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>5</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>6</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>7</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>8</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>9</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>10</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>11</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>12</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>13</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>14</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>15</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>16</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>17</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>18</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>19</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>20</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>21</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>22</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>23</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>24</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>25</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>26</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>27</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>28</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>29</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>30</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>31</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>32</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
    <InputCreditCardNumber>1234567890</InputCreditCardNumber>
    <InputBookName>C Language</InputBookName>
    <InputQuantity>2</InputQuantity>
  </Request>
  <Request>
    <RequestID>33</RequestID>
    <InputAccountName>libing</InputAccountName>
    <InputAccountPassword>111111</InputAccountPassword>
