=== darrenyjy/qdhw/trunk/DistributedSystem/DSProject7Server/db/bank.dtd
<!ELEMENT Bank (BankInfo, BankAccount*)>
<!ELEMENT BankInfo (TotalDeposit)>
<!ELEMENT TotalDeposit (#PCDATA)>
<!ELEMENT BankAccount (AccountName, AccountBalance)>
<!ELEMENT AccountName (#PCDATA)>
<!ELEMENT AccountBalance (#PCDATA)>

=== darrenyjy/qdhw/trunk/DistributedSystem/DSProject7Server/db/bank.xml
<?xml version="1.0"?>
<!DOCTYPE Bank SYSTEM "bank.dtd" >
<Bank>
  <BankInfo>
    <TotalDeposit>600.0</TotalDeposit>
  </BankInfo>
  <BankAccount>
    <AccountName>A</AccountName>
    <AccountBalance>400.0</AccountBalance>
  </BankAccount>
  <BankAccount>
    <AccountName>B</AccountName>
    <AccountBalance>0</AccountBalance>
  </BankAccount>
  <BankAccount>
    <AccountName>C</AccountName>
    <AccountBalance>200.0</AccountBalance>
  </BankAccount>
</Bank>
