=== darrenyjy/qdhw/trunk/DistributedSystem/DSProject7Server/db/book_store.dtd
<!ELEMENT BookStore (BookRetailer, Book*)>
<!ELEMENT BookRetailer (Cash)>
<!ELEMENT Cash (#PCDATA)>
<!ELEMENT Book (BookName, BookAuthor, BookPublisher, BookPrice, BookInStock)>
<!ELEMENT BookName (#PCDATA)>
<!ELEMENT BookAuthor (#PCDATA)>
<!ELEMENT BookPublisher (#PCDATA)>
<!ELEMENT BookPrice (#PCDATA)>
<!ELEMENT BookInStock (#PCDATA)>

=== darrenyjy/qdhw/trunk/DistributedSystem/DSProject3/db/book_store.xml
<?xml version="1.0"?>
<!DOCTYPE BookStore SYSTEM "book_store.dtd" >
<BookStore>
  <BookRetailer>
    <Cash>121792.0</Cash>
  </BookRetailer>
  <Book>
    <BookName>C Language</BookName>
    <BookAuthor>Mike</BookAuthor>
    <BookPublisher>Princeton</BookPublisher>
    <BookPrice>34.00</BookPrice>
    <BookInStock>8420</BookInStock>
  </Book>
  <Book>
    <BookName>Java Basics</BookName>
    <BookAuthor>Smith</BookAuthor>
    <BookPublisher>ASU</BookPublisher>
    <BookPrice>45.00</BookPrice>
    <BookInStock>40</BookInStock>
  </Book>
  <Book>
    <BookName>.NET Tutorial</BookName>
    <BookAuthor>Thomas</BookAuthor>
    <BookPublisher>UCLA</BookPublisher>
    <BookPrice>54.00</BookPrice>
    <BookInStock>200</BookInStock>
  </Book>
</BookStore>
