=== darrenyjy/qdhw/trunk/DistributedSystem/DSProject8Server/db/movie_store.dtd
<!ELEMENT MovieStore (MovieRetailer, Movie*)>
<!ELEMENT MovieRetailer (Cash)>
<!ELEMENT Cash (#PCDATA)>
<!ELEMENT Movie (MovieName, MovieAuthor, MoviePublisher, MoviePrice, MovieInStock)>
<!ELEMENT MovieName (#PCDATA)>
<!ELEMENT MovieAuthor (#PCDATA)>
<!ELEMENT MoviePublisher (#PCDATA)>
<!ELEMENT MoviePrice (#PCDATA)>
<!ELEMENT MovieInStock (#PCDATA)>

=== darrenyjy/qdhw/DistributedSystem/DSProject8Server/db/movie_store.xml
<?xml version="1.0"?>
<!DOCTYPE MovieStore SYSTEM "movie_store.dtd" >
<MovieStore>
  <MovieRetailer>
    <Cash>873522.0</Cash>
  </MovieRetailer>
  <Movie>
    <MovieName>C Language</MovieName>
    <MovieAuthor>Mike</MovieAuthor>
    <MoviePublisher>Princeton</MoviePublisher>
    <MoviePrice>34.00</MoviePrice>
    <MovieInStock>3992</MovieInStock>
  </Movie>
  <Movie>
    <MovieName>Java Basics</MovieName>
    <MovieAuthor>Smith</MovieAuthor>
    <MoviePublisher>ASU</MoviePublisher>
    <MoviePrice>45.00</MoviePrice>
    <MovieInStock>2680</MovieInStock>
  </Movie>
  <Movie>
    <MovieName>.NET Tutorial</MovieName>
    <MovieAuthor>Thomas</MovieAuthor>
    <MoviePublisher>UCLA</MoviePublisher>
    <MoviePrice>54.00</MoviePrice>
    <MovieInStock>200</MovieInStock>
  </Movie>
</MovieStore>
