=== darrenyjy/qdhw/trunk/DistributedSystem/DSProject8Server/db/object_registry.dtd
<!ELEMENT ObjectRegistry (ObjectSubscription*)>
<!ELEMENT ObjectSubscription (ObjectName, Method*)>
<!ELEMENT ObjectName (#PCDATA)>
<!ELEMENT Method (MethodName, Parameter*, ReturnValue)>
<!ELEMENT MethodName (#PCDATA)>
<!ELEMENT Parameter (ParameterType, ParameterDescription)>
<!ELEMENT ParameterType (#PCDATA)>
<!ELEMENT ParameterDescription (#PCDATA)>
<!ELEMENT ReturnValue (ReturnValueType, ReturnValueDescription)>
<!ELEMENT ReturnValueType (#PCDATA)>
<!ELEMENT ReturnValueDescription (#PCDATA)>

=== darrenyjy/qdhw/trunk/DistributedSystem/DSProject8Server/db/object_registry.xml
<?xml version="1.0"?>
<!DOCTYPE ObjectRegistry SYSTEM "object_registry.dtd">
<ObjectRegistry>
  <ObjectSubscription>
    <ObjectName>Amazon1.com</ObjectName>
    <Method>
      <MethodName>getPrice</MethodName>
      <Parameter>
        <ParameterType>String</ParameterType>
        <ParameterDescription>bookName</ParameterDescription>
      </Parameter>
      <ReturnValue>
        <ReturnValueType>float</ReturnValueType>
        <ReturnValueDescription>bookPrice</ReturnValueDescription>
      </ReturnValue>
    </Method>
    <Method>
      <MethodName>getPublisher</MethodName>
      <Parameter>
        <ParameterType>String</ParameterType>
        <ParameterDescription>bookName</ParameterDescription>
      </Parameter>
      <ReturnValue>
        <ReturnValueType>String</ReturnValueType>
        <ReturnValueDescription>publisher</ReturnValueDescription>
      </ReturnValue>
    </Method>
    <Method>
      <MethodName>getAuthor</MethodName>
      <Parameter>
        <ParameterType>String</ParameterType>
        <ParameterDescription>bookName</ParameterDescription>
      </Parameter>
      <ReturnValue>
        <ReturnValueType>String</ReturnValueType>
        <ReturnValueDescription>author</ReturnValueDescription>
      </ReturnValue>
    </Method>
    <Method>
      <MethodName>buyBooks</MethodName>
      <Parameter>
        <ParameterType>String</ParameterType>
        <ParameterDescription>accountName</ParameterDescription>
      </Parameter>
      <Parameter>
        <ParameterType>String</ParameterType>
        <ParameterDescription>accountPassword</ParameterDescription>
      </Parameter>
      <Parameter>
        <ParameterType>String</ParameterType>
        <ParameterDescription>creditCardNumber</ParameterDescription>
      </Parameter>
      <Parameter>
        <ParameterType>String</ParameterType>
        <ParameterDescription>bookName</ParameterDescription>
      </Parameter>
      <Parameter>
        <ParameterType>int</ParameterType>
        <ParameterDescription>quantity</ParameterDescription>
      </Parameter>
      <ReturnValue>
        <ReturnValueType>Hashtable</ReturnValueType>
        <ReturnValueDescription>receipt</ReturnValueDescription>
      </ReturnValue>
    </Method>
  </ObjectSubscription>
</ObjectRegistry>
